# ================= 纯中文名称字典（只需维护中文名） =================
TICKER_TRANSLATIONS = {
    "apple inc.": "苹果",
    "apple": "苹果",
    "microsoft corporation": "微软",
    "microsoft": "微软",
    "nvidia corporation": "英伟达",
    "nvidia": "英伟达",
    "amazon.com, inc.": "亚马逊",
    "amazon": "亚马逊",
    "meta platforms, inc.": "Meta",
    "meta": "Meta",
    "tesla, inc.": "特斯拉",
    "tesla": "特斯拉",
    "broadcom inc.": "博通",
    "broadcom": "博通",
    "the home depot, inc.": "家得宝",
    "home depot": "家得宝",
    "abbvie inc.": "艾伯维",
    "abbvie": "艾伯维",
    "texas instruments incorporated": "德州仪器",
    "texas instruments": "德州仪器",
    "chevron corporation": "雪佛龙",
    "chevron": "雪佛龙",
    "exxon mobil corporation": "埃克森美孚",
    "exxon mobil": "埃克森美孚",
    "jpmorgan chase & co.": "摩根大通",
    "jpmorgan": "摩根大通",
    "johnson & johnson": "强生",
    "taiwan semiconductor manufacturing company limited": "台积电",
    "tsmc": "台积电",
    "asml holding n.v.": "阿斯麦",
    "asml": "阿斯麦",
    "advanced micro devices, inc.": "超威半导体",
    "amd": "超威半导体",
    "salesforce, inc.": "赛富时",
    "salesforce": "赛富时",
    "nextera energy, inc.": "新纪元能源",
    "nextera energy": "新纪元能源",
    "the southern company": "南方电力",
    "southern co": "南方电力",
    "duke energy corporation": "杜克能源",
    "duke energy": "杜克能源",
    "sempra": "桑普拉能源",
    "american electric power company, inc.": "美国电力",
    "aep": "美国电力",
    "berkshire hathaway inc.": "伯克希尔",
    "alphabet inc.": "谷歌",
    "eli lilly and company": "礼来",
    "walmart inc.": "沃尔玛",
    "unitedhealth group incorporated": "联合健康",
    "visa inc.": "维萨",
    "costco wholesale corporation": "好市多",
    "netflix, inc.": "网飞",
    "pepsico, inc.": "百事可乐",
    "adobe inc.": "奥多比",
    "cisco systems, inc.": "思科",
    "qualcomm incorporated": "高通",
    "applied materials, inc.": "应用材料",
    "lam research corporation": "泛林集团",
    "micron technology, inc.": "美光科技",
    "analog devices, inc.": "亚德诺半导体",
    "kla corporation": "科磊",
    "intel corporation": "英特尔",
    "marvell technology, inc.": "美满电子",
    "microchip technology incorporated": "微芯科技",
    "accenture plc": "埃森哲",
    "oracle corporation": "甲骨文",
    "international business machines corporation": "IBM",
    "intuit inc.": "直觉软件",
    "blackrock, inc.": "贝莱德",
    "lockheed martin corporation": "洛克希德马丁",
    "amgen inc.": "安进",
    "pfizer inc.": "辉瑞",
    "united parcel service, inc.": "联合包裹",
    "verizon communications inc.": "威瑞森",
    "the coca-cola company": "可口可乐",
    "bristol-myers squibb company": "百时美施贵宝",
    "emerson electric co.": "艾默生电气",
    "merck & co., inc.": "默沙东",
    "bank of america corporation": "美国银行",
    "constellation energy corporation": "星座能源",
    "dominion energy, inc.": "自治领能源",
    "public service enterprise group incorporated": "公共服务企业",
    "consolidated edison, inc.": "爱迪生联合",
    "wec energy group, inc.": "WEC能源",
    "xcel energy inc.": "卓越能源",
    "edison international": "爱迪生国际",
    "american water works company, inc.": "美国水务",
    "dte energy company": "DTE能源",
    "ppl corporation": "PPL电力"
}

def smart_translate(raw_name, symbol):
    """自动对齐格式：强制输出为 中文 (Ticker) 形式"""
    if not raw_name:
        return f"未知 ({symbol})"
    cleaned_key = str(raw_name).strip().lower()
    
    # 获取纯中文名，如果字典里没有则降级使用原始英文
    cn_name = TICKER_TRANSLATIONS.get(cleaned_key, raw_name)
    
    # 强制进行格式校验：如果名字里还没带括号代码，自动补齐
    if f"({symbol})" in cn_name or f"（{symbol}）" in cn_name:
        return cn_name
    return f"{cn_name} ({symbol})"
